# Generated by Django 3.0.8 on 2020-07-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emplacement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emplacement',
        ),
    ]
