# Generated by Django 3.0.8 on 2020-07-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emplacement',
            options={'verbose_name': 'Emplacement de dossiers', 'verbose_name_plural': 'Emplacements de dossiers'},
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='app.Agent')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='app.Dossier')),
                ('emplacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='app.Emplacement')),
            ],
            options={
                'verbose_name': 'Mouvement de dossier',
                'verbose_name_plural': 'Mouvements de dossiers',
                'ordering': ['dossier', 'creation_time'],
            },
        ),
    ]
