# Generated by Django 3.0.8 on 2020-07-06 15:19

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20200706_1500'),
        ('app', '0005_auto_20200706_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='state',
            field=river.models.fields.state.StateField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.State'),
        ),
    ]
