# Generated by Django 3.0.8 on 2020-07-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dossier_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'permissions': [('can_manipulate_folders', 'Can manipulate folders')], 'verbose_name': 'Dossier', 'verbose_name_plural': 'Dossiers'},
        ),
    ]
