# Generated by Django 3.0.8 on 2020-07-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200706_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='emplacement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='app.Emplacement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dossier',
            name='categorie_dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='app.FolderCategory'),
        ),
    ]
