# Generated by Django 3.0.8 on 2020-08-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierOut',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Rapport - Liste des dossiers out',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.dossier',),
        ),
    ]
