# Generated by Django 3.0.8 on 2020-08-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '__first__'),
        ('Rapports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMouvement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.mouvement',),
        ),
        migrations.AlterModelOptions(
            name='dossierout',
            options={'verbose_name_plural': 'Dossiers hors de la salle d’archivage'},
        ),
    ]
